### ISSUE TITLE
Valheim-Plus Egg | Server not working

### ISSUE THREAD

**Issue by Vanheden** [gOOvER/Ptero-Dev-Eggs#1]
This is the log after a fresh install and startup

https://pastebin.com/R4wGyupn

**Comment by gOOvER** [comment]
Whats the Error?

**Comment by Vanheden** [comment]
I dont see any error when I try to connect to it nothing happens

**Comment by gOOvER** [comment]
new Server? Then you need to wait some minutes until the World gets generated

**Comment by Vanheden** [comment]
Gonna leave it on for a bit and see what happens

**Comment by gOOvER** [comment]
and pls change in

/home/container/BepInEx/config/valheim_plus.cfg
`enforceMod=on`

to

`enforceMod=off`

**Comment by Vanheden** [comment]
Failed to get join server data with enforceMod on/off

**Comment by gOOvER** [comment]
it must be off, because elso you get a Invalid Version Warning

**Comment by gOOvER** [comment]
send me pls ip:port on Discord

**Comment by gOOvER** [comment]
Wrong  Port coinfiguration
